// IPC channel names shared between the main process and the preload bridge.
// This module must stay free of electron/node imports so it can be safely
// loaded by the sandboxed preload script.
export const IPC = {
  openFolder: "dialog:openFolder",
  chooseNewSiteFolder: "dialog:chooseNewSiteFolder",
  projectOpen: "project:open",
  listThemes: "wizard:listThemes",
  createSite: "wizard:createSite",
  createPage: "page:create",
  gitStatus: "git:status",
  gitInit: "git:init",
  settingsReadGlobal: "settings:readGlobal",
  settingsWriteGlobal: "settings:writeGlobal",
  settingsRemoveRecent: "settings:removeRecent",
  settingsReadRepo: "settings:readRepo",
  settingsMerged: "settings:merged",
  fileRead: "file:read",
  fileWrite: "file:write",
  importImage: "assets:importImage",
  watchStart: "watch:start",
  watchStop: "watch:stop",
  externalChange: "watch:externalChange",
  pagesList: "pages:list",
  previewStart: "preview:start",
  previewStop: "preview:stop",
  previewLog: "preview:log",
  publish: "project:publish",
  updaterCheck: "updater:check",
  updaterDownload: "updater:download",
  updaterCancel: "updater:cancel",
  updaterInstall: "updater:install",
  updaterStatus: "updater-status",
  getAppVersion: "app:version",
  openConfigFolder: "app:openConfigFolder",
} as const;
